Installing-Heads.md
The old URL isn't found on `trmm.net`.
=> update SPI Flash URL

Installing-Heads.md
This is probably old and outdated. Powering off works just fine, for
quite some time. Tested myself on a few X230 devices too.
=> Installing-Heads: remove false ill effect of using me_cleaner

Building.md
Fedora libelf devel package name is elfutils-libelf-devel
=> Fedora libelf-devel package name correction

Installing-Heads.md
Previous text refers to creating a single file containing both private_stub and public key but never indicated how.
I successfully generated the keys from fedora-28 with gpg2 --card-edit. Couldn't with gpg (1.4.24) from fedora-28. Generating armor copies of the keys worked with gpg2 commands.
Note: I was not able to use cbfs commands of the following section and have a working head environment. I still can't figure what I did wrong. This needs to be tested more. using gui-init and integrating the keys into running/referenced roms worked out of the box with keys concatenated.
=> Adding command to concatenate keys

Building.md
I was attempting to build Heads from current git master, but the build failed here:
```
2019-02-19 00:08:45+00:00 CONFIG cairo
make[1]: *** [Makefile:356: /root/heads/build/cairo-1.14.12/.configured] Error 1
make[1]: Leaving directory '/root/heads'
Makefile:561: recipe for target 'all' failed
make: *** [all] Error 2
```
Looking at the build log for cairo, I found this:
```
checking for i386-elf-linux-pkg-config... no
checking for pkg-config... no
configure: error: pkg-config >=  required but not found (http://pkgconfig.freedesktop.org/)
```
I ran into this error on both Debian 9 and Ubuntu 16.04 (LXC images from linuxcontainers.org). The build ran successfully after installing pkg-config. I'm not sure if bare-metal distro images would have it preinstalled, but the LXC images at least do …
=> Add pkg-config to required Debian dependencies

index.md
This fixes the now broken link to YouTube where the video was taken down.
=> Change link to Peter Stuge's talk to media.ccc.de

Beginner-Installation-Guide.md
This new file contains a guide that beginners can follow to install Heads without any prior experience.
After struggling to install Heads, I noticed that the existing installation documentation is scattered. Some is contained in Building.md, Installing-Heads.md, Clean-the-ME-firmware.md and in other files. The files you need to reference if you are installing for the first time are not ordered and you have to move back and forth.
While it is good that the detailed documentation is there for those who can understand it, I think that there should be at least a succinct first installation guide for new users. The guide I have proposed is not complete and I plan to add pictures that further detail the steps. However, I think that even in its current state it would be helpful to the project.
=> Add a Thorough Guide for Beginners

Keys.md
Documentation changes linked to PCR usage in coreboot 4.8.1 and newer versions, to be applied at the same time as https://github.com/osresearch/heads/pull/793 is merged.
Linked to VBOOT+Measured boot/Measured boot changes applied directly in coreboot so that we have a common base prior of going https://github.com/osresearch/heads/pull/709 and https://github.com/osresearch/heads/pull/721 
@PatrickRudolph comments welcome
=> PCR documentation usage changes for coreboot 4.8.1 and newer versions

Beginner-Installation-Guide.md, Boot.md, Building.md, Clean-the-ME-firmware.md, Emulating-Heads.md, GPG.md, Installing-Heads.md, Keys.md, Porting.md, Upgrading.md, _config.yml, index.md
Demo of changes can be viewed here: https://thrilleratplay.github.io/heads-wiki/
This is an attempt to create smaller incremental changes I mentioned in a comment in #25 .
=> Change theme for easier navigation

_config.yml
Checking out the updated theme for the head wiki and noticed the "Edit this page on Github" links are pointing to the gh-pages branch instead of master.
=> fix(config.yml): change gh_edit_branch to master

Community.md, Development/Contributing-to-Heads-Wiki.md, Development/index.md
Added note about contributing to the wiki.  Can be viewed here https://thrilleratplay.github.io/heads-wiki/Contributing-to-Heads-wiki/
=> docs: add contributing to wiki section

Installing-and-Configuring/Building-Heads/general.md, Installing-and-Configuring/Building-Heads/index.md, Installing-and-Configuring/Building-Heads/kgpe-d16.md, Installing-and-Configuring/Building-Heads/t420.md, Installing-and-Configuring/Building-Heads/t430.md, Installing-and-Configuring/Building-Heads/x220.md, Installing-and-Configuring/Building-Heads/x230.md
Can be viewed: [https://tonux599.github.io/heads-wiki/](https://tonux599.github.io/heads-wiki/)
Commit message outlines:
> Split up 'Step 1 - Building Heads' as it had references to the X230 board in it's main guide. This split has moved general information into 'General Building' and X230 specific to 'Lenovo X230' while keeping it all under the same 'Step 1 - Building Heads' heading. Template/WIP pages for some other boards.
If everyone is happy with this and its merged. I can base my upcoming KGPE-D16 docs on it.
=> Split up 'Building Heads' with board specifics

Installing-and-Configuring/install-os.md
Replaces #91 
Qubes 4.1 needs to be installed over Heads supporting cryptsetup2. (as of now, this doesn't include xx20 boards configuations.)
=> Qubes 4.1 installation instructions update.

About/Keys.md, Community.md, Development/Contributing-to-Heads-Wiki.md, Installing-and-Configuring/Building-Heads/general.md, Installing-and-Configuring/Downloading.md, Installing-and-Configuring/Prerequisites.md, Installing-and-Configuring/Upgrading.md, Installing-and-Configuring/index.md, index.md
WiP. 
**_As of now changes are visible from these pages:_** 
- https://tlaurion.github.io/heads-wiki/ (added another Step 1 - Downloading)
- https://tlaurion.github.io/heads-wiki/Downloading
- https://tlaurion.github.io/heads-wiki/Updating
- https://tlaurion.github.io/heads-wiki/Prerequisites
- https://tlaurion.github.io/heads-wiki/community/
- https://tlaurion.github.io/heads-wiki/Keys/#tpm-pcrs (to end of page)
**Present goals of this PR**:
=> Firmware download/upgrade/prerequisites cleanup 

Installing-and-Configuring/Building-Heads/x230-maximized.md, Installing-and-Configuring/Building-Heads/x230.md, Installing-and-Configuring/Flashing-Guides/x230-maximized.md
Separate Legacy build and flashing instructions from Maximized builds. 
Touches 2 pages:
https://tlaurion.github.io/heads-wiki/x230-building/
https://tlaurion.github.io/heads-wiki/x230-flashing/
Adds two pages:
https://tlaurion.github.io/heads-wiki/x230-maximized-building/
https://tlaurion.github.io/heads-wiki/x230-maximized-flashing/
=> x230: Seperate building and install guides between Legacy and Maximized

Development/Emulating-Heads.md, Development/Porting.md, Development/make-details.md, Installing-and-Configuring/Building-Heads/general.md, Installing-and-Configuring/Building-Heads/x230.md, Installing-and-Configuring/Flashing-Guides/Clean-the-ME-firmware.md, Installing-and-Configuring/Flashing-Guides/x230-maximized.md, Installing-and-Configuring/Flashing-Guides/x230.md, Installing-and-Configuring/Upgrading.md
Since PPC64 support was added, x86 has been made the default architecture while PPC64 can be selected and is used for Talos II boards. This changed paths for:
- install -> install/x86
- packages -> packages/x86
- build -> build/x86
This PR changes those references accordingly to fix #104 per user report on slack/matrix channel.
----
Some additional cleanup:
- Also adapt porting guide to use automatic arch tuple from `$(MUSL_ARCH)`
- remove references to locally built make (was deleted a while ago)
=> Adapt documentation after PPC64LE architecture addition (build/ ->  build/x86 refs)

README.md
Reverts last commit since osresearch.net is back. 
Bonus: URL points to https instead of http
=> README: point to https://osresearch.net again (DNS name renewed)

Development/make-details.md
`*.intermediate` target name does not seem to work anymore, does it?
=> How to build one submodule

Installing-and-Configuring/Building-Heads/general.md
Reflect https://github.com/linuxboot/heads/pull/1661 changes
closes #152
=> General build instructions: update documentation since Nix buildstack is now used

Installing-and-Configuring/install-os.md
Update doc so that users are made aware that they should remove all USB Security dongles first at that are not the one bound to Heads.
=> Update install-os.md following https://github.com/linuxboot/heads/issues/1717 issue

Installing-and-Configuring/configuring-keys.md
80 chars wide, typos and images which urls were broken from a9c64ad3e84c1210f5ddd7cc62dd52fb1457969e
=> Installing-and-Configuring/configuring-keys.md: fix typos and images url

Installing-and-Configuring/Downloading.md, Installing-and-Configuring/Upgrading.md
Fixes #186 
Until merged:
- Download instructions rendered at https://tlaurion.github.io/heads-wiki/Downloading
- Upgrading/Updating instructions rendered at https://tlaurion.github.io/heads-wiki/Updating
- Changes can be seen looking at commit changes below or through https://github.com/linuxboot/heads-wiki/commit/f2400744b37362f185b6b555b0e99d642d7b4b7d.patch
Details: 
- less is more (remove duplicates between the pages, cross ref when needed, simplify)
- renew screenshots that got deprecated. remove unneeded ones.
- Cleanup global warning when flashing without having an external programmer to unbrick
- clarify maximized vs legacy, remove instructions for migration, add Nitrokey support channel for firmware prior of 1.3 to get flashing service if using legacy version
- Add notes for …
=> Downloading.md + Upgrading.md: massive cleanup

index.md
Fixes https://github.com/linuxboot/heads-wiki/issues/188
(Putting this as context for future linuxboot+kexec+linux kernel simpledrm related needed collaboration)
---
commit log:
This shows the power of using fbwhiptail/fbwhiptail to drive menus under Heads.
Whiptail is command-line utility used in shell scripts to create text-based user interfaces (TUIs) in a terminal (console). FBwhiptail is a whiptail wrapper, aimed at driving a reduced feature set of whiptail but for high resolution Frame Buffer (FB), intruduced by Purism.
By using Whiptail in the shell scripts, we are able to drive both high resolution graphics for laptops and workstations into coreboot initialized simple framebuffer, picked up by efifb linux kernel driver, which permits us to kexec into a full featured linux kernel, …
=> index.md: show both fbwhiptail(high res)/whiptail(low res) main menu

index.md
This unrecorded conference: https://lfms25.sched.com/event/1urX2/deploying-linux-as-firmware-at-global-scale-update-ronald-minnich-hewlett-packard
PDF saved through https://github.com/linuxboot/heads-wiki/issues/191
Closes #191 
TODO: maybe switch to archive.org but wasn't able to save archive of it and archive.as same story.
=> index.md: add '2025 - Linux Foundation Member Summit - Ronald (Ron) Minnich - Deploying Linux as Firmware at Global Scale: Update' presentation paper
